stages:
- name: 编译
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: mvn clean install -Dmaven.test.skip=true
- name: 打包镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: java-demo:20190822
      pushRemote: true
      registry: 127.0.0.1:34662
timeout: 30
notification:
  recipients:
  - recipient: '#c5game'
    notifier: c-jphrs:n-fffc6
  condition:
  - Success
  - Changed
  - Failed
